tinymce.PluginManager.add('addquicktags', function(editor) {

	// 新パーツ
	var csMenuItems = [
	
	{ text: 'ヘッドA(白字・中央寄)', menu: [
			{ text: 'デザイン1(本棚)', data: '<table class="headParts001" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head001_bg.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts001_container">\n<div class="headParts001_content">\n<div class="headParts001_content_inner">\n<div class="headParts001_subTitle_wrap">\n<p class="headParts001_subTitle">こちらにヘッドテキストを入力</p>\n</div>\n<p class="headParts001_mainTitle">ヘッドテキストを入力</p>\n<p class="headParts001_txt">テキストを入力テキストを入力テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、<br />\nレイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい</p>\n</div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: 'デザイン2(海と崖)', data: '<table class="headParts001" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head001_bg2.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts001_container">\n<div class="headParts001_content">\n<div class="headParts001_content_inner">\n<div class="headParts001_subTitle_wrap">\n<p class="headParts001_subTitle">こちらにヘッドテキストを入力</p>\n</div>\n<p class="headParts001_mainTitle">ヘッドテキストを入力</p>\n<p class="headParts001_txt">テキストを入力テキストを入力テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、<br />\nレイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい</p>\n</div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: 'デザイン3(本と緑)', data: '<table class="headParts001" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head001_bg3.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts001_container">\n<div class="headParts001_content">\n<div class="headParts001_content_inner">\n<div class="headParts001_subTitle_wrap">\n<p class="headParts001_subTitle">こちらにヘッドテキストを入力</p>\n</div>\n<p class="headParts001_mainTitle">ヘッドテキストを入力</p>\n<p class="headParts001_txt">テキストを入力テキストを入力テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、<br />\nレイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい</p>\n</div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
				{ text: 'デザイン4(浜辺)', data: '<table class="headParts001" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/formback_sea-scaled.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts001_container">\n<div class="headParts001_content">\n<div class="headParts001_content_inner">\n<div class="headParts001_subTitle_wrap">\n<p class="headParts001_subTitle">こちらにヘッドテキストを入力</p>\n</div>\n<p class="headParts001_mainTitle">ヘッドテキストを入力</p>\n<p class="headParts001_txt">テキストを入力テキストを入力テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、<br />\nレイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい</p>\n</div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
					]},
					
					
						{ text: 'ヘッドB(黒字・左寄)', menu: [	
			{ text: 'デザイン1(パソコン)', data: '<table class="headParts002" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head002_bg.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts002_container po_r">\n<div class="headParts002_content">\n<div class="headParts002_content_inner">\n<p class="headParts002_subTitle">ヘッドテキストを入力ヘッドテキストを入力ヘッドテキストを入力ヘッドテキストを入力</p>\n<p class="headParts002_mainTitle">ヘッドテキストを入力</p>\n<p class="headParts002_txt">テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、レイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい</p>\n</div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: 'デザイン2(海と本)', data: '<table class="headParts002" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head002_bg2.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts002_container po_r">\n<div class="headParts002_content">\n<div class="headParts002_content_inner">\n<p class="headParts002_subTitle">ヘッドテキストを入力ヘッドテキストを入力ヘッドテキストを入力ヘッドテキストを入力</p>\n<p class="headParts002_mainTitle">ヘッドテキストを入力</p>\n<p class="headParts002_txt">テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、レイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい</p>\n</div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
				{ text: 'デザイン3(コーヒーとPC)', data: '<table class="headParts002" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head002_bg3.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts002_container po_r">\n<div class="headParts002_content">\n<div class="headParts002_content_inner">\n<p class="headParts002_subTitle">ヘッドテキストを入力ヘッドテキストを入力ヘッドテキストを入力ヘッドテキストを入力</p>\n<p class="headParts002_mainTitle">ヘッドテキストを入力</p>\n<p class="headParts002_txt">テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、レイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい</p>\n</div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'デザイン4(ピンクの花)', data: '<table class="headParts002" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head002_bg4.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts002_container po_r">\n<div class="headParts002_content">\n<div class="headParts002_content_inner">\n<p class="headParts002_subTitle">ヘッドテキストを入力ヘッドテキストを入力ヘッドテキストを入力ヘッドテキストを入力</p>\n<p class="headParts002_mainTitle">ヘッドテキストを入力</p>\n<p class="headParts002_txt">テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、レイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい</p>\n</div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		
					]},
					
					
						{ text: 'ヘッドC(黒字・左寄｜画像右）', menu: [	
			{ text: 'デザイン1(シンプル模様)', data: '<table class="headParts003" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head003_bg.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts003_container po_r">\n<div class="headParts003_content">\n<div class="headParts003_content_left">\n<div class="headParts003_ttl_wrap">\n<p class="headParts003_subTitle">ヘッドテキストを入力</p>\n<p class="headParts003_mainTitle">ヘッドテキストを入力</p>\n</div>\n<p class="headParts003_txt">テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、レイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい\n右の画像クラスはshadow-borderです</p>\n</div>\n<div class="headParts003_content_right"><img class="shadow-border" src="https://lptemp.com/dx/wp-content/uploads/2020/01/insert-image.jpg" alt="" width="960" height="600" /></div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: 'デザイン2(PC)', data: '<table class="headParts003" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head003_bg2.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts003_container po_r">\n<div class="headParts003_content">\n<div class="headParts003_content_left">\n<div class="headParts003_ttl_wrap">\n<p class="headParts003_subTitle">ヘッドテキストを入力</p>\n<p class="headParts003_mainTitle">ヘッドテキストを入力</p>\n</div>\n<p class="headParts003_txt">テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、レイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい\n右の画像クラスはshadow-borderです</p>\n</div>\n<div class="headParts003_content_right"><img class="shadow-border" src="https://lptemp.com/dx/wp-content/uploads/2020/01/insert-image.jpg" alt="" width="960" height="600" /></div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: 'デザイン3(パーティー)', data: '<table class="headParts003" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head003_bg3.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts003_container po_r">\n<div class="headParts003_content">\n<div class="headParts003_content_left">\n<div class="headParts003_ttl_wrap">\n<p class="headParts003_subTitle">ヘッドテキストを入力</p>\n<p class="headParts003_mainTitle">ヘッドテキストを入力</p>\n</div>\n<p class="headParts003_txt">テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、レイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい\n右の画像クラスはshadow-borderです</p>\n</div>\n<div class="headParts003_content_right"><img class="shadow-border" src="https://lptemp.com/dx/wp-content/uploads/2020/01/insert-image.jpg" alt="" width="960" height="600" /></div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
	{ text: 'デザイン4(食べ物)', data: '<table class="headParts003" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head003_bg5.jpg\');">\n<tbody>\n<tr>\n<td>\n<div class="headParts003_container po_r">\n<div class="headParts003_content">\n<div class="headParts003_content_left">\n<div class="headParts003_ttl_wrap">\n<p class="headParts003_subTitle">ヘッドテキストを入力</p>\n<p class="headParts003_mainTitle">ヘッドテキストを入力</p>\n</div>\n<p class="headParts003_txt">テキストを入力テキストを入力テキストを入力<br />\nヘッドパーツのテキストを改行する時は、レイアウト崩れを防ぐため「Shiftキー」を押しながら改行を行って下さい\n右の画像クラスはshadow-borderです</p>\n</div>\n<div class="headParts003_content_right"><img class="shadow-border" src="https://lptemp.com/dx/wp-content/uploads/2020/01/insert-image.jpg" alt="" width="960" height="600" /></div>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
	]},
	
	
		{ text: 'サブヘッドA(帯)', menu: [	
			{ text: '補足テキストなし', data: '<table class="subHeadParts004" style="background-color: #0064e0;">\n<tbody>\n<tr>\n<td>\n<div class="subHeadParts004_container">\n<p>サブヘッドテキストを入力</p>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: '補足テキストあり', data: '<table class="subHeadParts004" style="background-color: #0064e0;">\n<tbody>\n<tr>\n<td>\n<div class="subHeadParts004_container">\n<p>サブヘッドテキストを入力</p>\n<p class="subHeadParts004_txt">こちらに補足テキストを入力。ここを改行する時はShiftキーを押しながら改行して下さい</p>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		]},
	
	
	{ text: 'サブヘッドB(吹き出し)', menu: [		
			{ text: '補足テキストなし', data: '<table class="subHeadParts001" style="background-color: #0064e0;">\n<tbody>\n<tr>\n<td>\n<div class="subHeadParts001_container">\n<p>サブヘッドテキストを入力</p>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>\n<p>&nbsp;</p>'},
			{ text: '補足テキストあり', data: '<table class="subHeadParts001" style="background-color: #0064e0;">\n<tbody>\n<tr>\n<td>\n<div class="subHeadParts001_container">\n<p>サブヘッドテキストを入力</p>\n<p class="subHeadParts001_txt">こちらに補足テキストを入力。ここを改行する時はShiftキーを押しながら改行して下さい</p>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>\n<p>&nbsp;</p>'},
		]},
	
	
	
		{ text: 'サブヘッドC(＼補足テキスト／)', menu: [					
			{ text: '補足テキストあり', data: '<table class="subHeadParts002">\n<tbody>\n<tr>\n<td>\n<div class="subHeadParts002_container">\n<div class="subHeadParts002_subTitle_wrap">\n<p class="subHeadParts002_subTitle">補足テキストを入力できます。ここを改行をするときは、<br />\nレイアウト崩れを防ぐためShiftキーを押しながら改行して下さい</p>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<table class="subHeadParts002" style="background-color: #00706b;">\n<tbody>\n<tr>\n<td>\n<div class="subHeadParts002_mainTitle_wrap">\n<div class="subHeadParts002_container">\n<p>サブヘッドテキストを入力</p>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		]},
	
	
	
	
	{ text: '小見出し', menu: [
			{ text: '小見出し(グレー背景)', data: '<table style="background-color: #f0f0f0;  height: 70px;">\n<tbody>\n<tr>\n<td style="padding: 0 10px;"><p>テキストを入力</p></td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: '＼補足テキスト／', data: '<table class="subHeadParts002">\n<tbody>\n<tr>\n<td>\n<div class="subHeadParts002_container">\n<div class="subHeadParts002_subTitle_wrap">\n<p class="subHeadParts002_subTitle">補足テキストを入力できます。ここを改行をするときは、<br />\nレイアウト崩れを防ぐためShiftキーを押しながら改行して下さい</p>\n</div>\n</div>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		]},
		
		
		
		
					{ text: '登録フォーム(背景あり)', menu: [
		{ text: '定番｜青', data: '<table class="formbox box1 form1 form-a1 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/foramback_beach.jpg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a1"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
			{ text: 'モダン｜青', data: '<table class="formbox box2 form2 form-a1 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/foramback_beach.jpg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a1"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
						{ text: 'モダン｜緑', data: '<table class="formbox box3 form2 form-a2 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/formback_green.jpg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a2"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
						
						{ text: 'モダン｜黄色', data: '<table class="formbox box1 form2 form-a3 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/formback_library.jpg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a3"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
						
						{ text: 'モダン｜ピンク', data: '<table class="formbox box1 form2 form-a4 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/formback_flower.jpg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a4"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
						
						{ text: 'モダン｜紫色', data: '<table class="formbox box1 form2 form-a5 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/formback_wall.jpg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a5"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
						
						{ text: 'モダン｜青〜紫', data: '<table class="formbox box1 form2 form-a6 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/formback_sunsetsea.jpeg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a6"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
						
						{ text: '定番｜ベージュ', data: '<table class="formbox box1 form2 form-b1 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/formback_building.jpeg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b1"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
						
						{ text: '定番｜茶色', data: '<table class="formbox box2 form2 form-b2 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/formback_world.jpg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b2"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
						
						{ text: '定番｜赤色', data: '<table class="formbox box3 form2 form-b3 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/formback_cooking.jpg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b3"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
						
						{ text: '定番｜黄緑', data: '<table class="formbox box1 form2 form-b4 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/formback_book.jpg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b4"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
						
						{ text: '定番｜空色', data: '<table class="formbox box1 form2 form-b5 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/head002_bg2.jpg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b5"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
						
						{ text: '定番｜グレー', data: '<table class="formbox box1 form2 form-b6 full-width" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/formback_architecture.jpg\');" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td class="header">\n<h2>登録はこちらから</h2>\n<p>【こちらにテキストを入力】本フォームに登録する事で、登録した人が何を得られるのか？それによって、どういうメリットやベネフィットがあり、どういう未来に行けるのかなどを、こちらで伝える事をオススメいたします。</p>\n</td>\n<td class="section">\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b6"><button name="submit" type="submit">登録する<br /><small>サブテキスト</small></button></div>\n</form>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
				]},
				
				
			
			{ text: '登録フォーム(背景なし)', menu: [		
			{ text: '定番｜青', data: '<table class="formbox box1 form1 form-a1 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a1"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
			{ text: 'モダン｜青', data: '<table class="formbox box2 form2 form-a1 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a1"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
			{ text: 'モダン｜緑', data: '<table class="formbox box3 form2 form-a2 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a2"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
			{ text: 'モダン｜黄色', data: '<table class="formbox box1 form2 form-a3 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a3"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
			{ text: 'モダン｜ピンク', data: '<table class="formbox box1 form2 form-a4 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a4"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
			{ text: 'モダン｜紫色', data: '<table class="formbox box1 form2 form-a5 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a5"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
			{ text: 'モダン｜青〜紫', data: '<table class="formbox box1 form2 form-a6 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-a6"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
			{ text: '定番｜ベージュ', data: '<table class="formbox box1 form2 form-b1 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b1"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
			{ text: '定番｜茶色', data: '<table class="formbox box2 form2 form-b2 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b2"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
			{ text: '定番｜赤色', data: '<table class="formbox box3 form2 form-b3 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b3"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			
			{ text: '定番｜黄緑', data: '<table class="formbox box1 form2 form-b4 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b4"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		
		{ text: '定番｜空色', data: '<table class="formbox box1 form2 form-b5 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b5"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		
		{ text: '定番｜グレー', data: '<table class="formbox box1 form2 form-b6 formonly" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<div class="iptgroup">\n<input name="d[1]" type="text" value="" placeholder="名前を入力" />\n<input name="d[0]" type="text" value="" placeholder="メールアドレスを入力" />\n</div>\n<div class="btn-n btn-s btn-b6"><button name="submit" type="submit">登録する<small>サブテキスト</small></button></div>\n<p>【こちらに注釈テキストを入力】例：登録後すぐに、《無料コンテンツ・状況に合わせて変更して下さい》を受け取る事ができます。記入されたメールアドレスに、自動返信メールをお送りいたしますので、ご確認下さい。</p>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		]},
		
		
	
	
	{ text: 'ボタン(四角)', menu: [
			{ text: 'モダン｜青', data: '<p class="btn-n btn-s btn-a1"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜緑', data: '<p class="btn-n btn-s btn-a2"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜黄', data: '<p class="btn-n btn-s btn-a3"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜ピンク', data: '<p class="btn-n btn-s btn-a4"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜紫色', data: '<p class="btn-n btn-s btn-a5"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜青〜紫', data: '<p class="btn-n btn-s btn-a6"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜ベージュ', data: '<p class="btn-n btn-s btn-b1"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜茶色', data: '<p class="btn-n btn-s btn-b2"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜赤', data: '<p class="btn-n btn-s btn-b3"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜黄緑', data: '<p class="btn-n btn-s btn-b4"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜水色', data: '<p class="btn-n btn-s btn-b5"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜グレー', data: '<p class="btn-n btn-s btn-b6"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},	
		]},
	

	
		{ text: 'ボタン(丸型)', menu: [
			{ text: 'モダン｜青', data: '<p class="btn-n btn-s btn-a1 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜緑', data: '<p class="btn-n btn-s btn-a2 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜黄', data: '<p class="btn-n btn-s btn-a3 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜ピンク', data: '<p class="btn-n btn-s btn-a4 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜紫色', data: '<p class="btn-n btn-s btn-a5 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜青〜紫', data: '<p class="btn-n btn-s btn-a6 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜ベージュ', data: '<p class="btn-n btn-s btn-b1 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜茶色', data: '<p class="btn-n btn-s btn-b2 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜赤', data: '<p class="btn-n btn-s btn-b3 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜黄緑', data: '<p class="btn-n btn-s btn-b4 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜水色', data: '<p class="btn-n btn-s btn-b5 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜グレー', data: '<p class="btn-n btn-s btn-b6 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
		]},
	
	
	
	{ text: 'ボタン(大サイズ・四角)', menu: [
			{ text: 'モダン｜青', data: '<p class="btn-n btn-l btn-a1"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜緑', data: '<p class="btn-n btn-l btn-a2"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜黄', data: '<p class="btn-n btn-l btn-a3"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜ピンク', data: '<p class="btn-n btn-l btn-a4"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜紫色', data: '<p class="btn-n btn-l btn-a5"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜青〜紫', data: '<p class="btn-n btn-l btn-a6"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜ベージュ', data: '<p class="btn-n btn-l btn-b1"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜茶色', data: '<p class="btn-n btn-l btn-b2"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜赤', data: '<p class="btn-n btn-l btn-b3"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜黄緑', data: '<p class="btn-n btn-l btn-b4"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜水色', data: '<p class="btn-n btn-l btn-b5"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜グレー', data: '<p class="btn-n btn-l btn-b6"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},	
		]},
	
	
	{ text: 'ボタン(大サイズ・丸型)', menu: [
			{ text: 'モダン｜青', data: '<p class="btn-n btn-l btn-a1 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜緑', data: '<p class="btn-n btn-l btn-a2 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜黄', data: '<p class="btn-n btn-l btn-a3 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜ピンク', data: '<p class="btn-n btn-l btn-a4 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜紫色', data: '<p class="btn-n btn-l btn-a5 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜青〜紫', data: '<p class="btn-n btn-l btn-a6 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜ベージュ', data: '<p class="btn-n btn-l btn-b1 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜茶色', data: '<p class="btn-n btn-l btn-b2 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜赤', data: '<p class="btn-n btn-l btn-b3 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜黄緑', data: '<p class="btn-n btn-l btn-b4 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜水色', data: '<p class="btn-n btn-l btn-b5 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},
			{ text: '定番｜グレー', data: '<p class="btn-n btn-l btn-b6 btn-round"><a href="#" target="_blank" rel="noopener noreferrer">テキストを入力<br /><small>こちらに補足テキストを入力できます</small></a></p>\n<p>&nbsp;</p>'},		
		]},
		
		
		
			{ text: '枠', menu: [
			{ text: 'モダン｜角丸枠1', data: '<table class="frame-1">\n<tbody>\n<tr>\n<td>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜角丸枠2', data: '<table class="frame-2" style="border: 5px solid; border-color: #394eea;">\n<tbody>\n<tr>\n<td>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜点線枠1', data: '<table class="frame-3" style="border: dashed 2px; border-color: #ddd;">\n<tbody>\n<tr>\n<td>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜点線枠2', data: '<table class="frame-4" style="border: dashed 1px; border-color: #ddd;">\n<tbody>\n<tr>\n<td>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜上下枠1', data: '<table class="frame-6" style="border: 10px solid; border-color: #ddd;">\n<tbody>\n<tr>\n<td>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: 'モダン｜上下枠2', data: '<table class="frame-7" style="border: solid 3px; border-color: #d9d9d9;">\n<tbody>\n<tr>\n<td>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: '定番｜四角', data: '<table class="shikaku" style="border: 1px solid #000000;" border="1">\n<tbody>\n<tr>\n<td>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: '定番｜角丸', data: '<table class="marukaku" style="border: 1px solid #000000;" border="1">\n<tbody>\n<tr>\n<td>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: '定番｜へこみ', data: '<table class="pressed">\n<tbody>\n<tr>\n<td>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: '定番｜浮出', data: '<table class="tableshadow">\n<tbody>\n<tr>\n<td>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n<p>こちらにテキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		]},
	
	
	
		{ text: 'ブレット(リスト)', menu: [
			{ text: '丸ブレット｜赤', data: '<ul class="List-oval_1">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: '丸ブレット｜青', data: '<ul class="List-oval_2">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: '丸ブレット｜緑', data: '<ul class="List-oval_3">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: '丸ブレット｜黄緑', data: '<ul class="List-oval_4">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: '丸ブレット｜灰色', data: '<ul class="List-oval_5">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: '丸ブレット｜薄い灰色', data: '<ul class="List-oval_6">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: 'チェック｜赤', data: '<ul class="List-chk-A_1">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: 'チェック｜青', data: '<ul class="List-chk-A_2">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: 'チェック｜緑', data: '<ul class="List-chk-A_3">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: 'チェック｜黄緑', data: '<ul class="List-chk-A_4">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: 'チェック｜灰色', data: '<ul class="List-chk-A_5">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: 'チェック｜薄い灰色', data: '<ul class="List-chk-A_6">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: '被せチェック｜赤', data: '<ul class="List-chk-B_1">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: '被せチェック｜青', data: '<ul class="List-chk-B_2">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: '被せチェック｜緑', data: '<ul class="List-chk-B_3">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: '被せチェック｜黄緑', data: '<ul class="List-chk-B_4">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: '被せチェック｜灰色', data: '<ul class="List-chk-B_5">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},
			{ text: '被せチェック｜薄い灰色', data: '<ul class="List-chk-B_6">\n<li>ここにテキストを入力</li>\n<li>ここにテキストを入力</li>\n<li>ブレット(リスト)内で改行する時は、<br />\nShiftキーを押しながら改行して下さい。</li>\n</ul>\n<p>&nbsp;</p>\n'},	
		]},
	
	
	
	{ text: '全幅枠', menu: [	
			{ text: '定番｜透過なし', data: '<table class="fullwidth_std" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/linedpaper.png\'); background-position: center;">\n<tbody>\n<tr>\n<td>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>&nbsp;</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},

			{ text: '定番｜透過なし・背景固定', data: '<table class="fullwidth_std" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/linedpaper.png\'); background-position: center; background-attachment: fixed;">\n<tbody>\n<tr>\n<td>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>&nbsp;</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},

			{ text: '定番｜黒透過', data: '<table class="fullwidth_std_black" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/beach-bench-boardwalk-clouds.jpg\'); background-position: center;">\n<tbody>\n<tr>\n<td>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>&nbsp;</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},

			{ text: '定番｜黒透過・背景固定', data: '<table class="fullwidth_std_black" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/beach-bench-boardwalk-clouds.jpg\'); background-position: center; background-attachment: fixed;">\n<tbody>\n<tr>\n<td>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>&nbsp;</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
	
			{ text: '定番｜白透過', data: '<table class="fullwidth_std_white" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/beach-bench-boardwalk-clouds.jpg\'); background-position: center;">\n<tbody>\n<tr>\n<td>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>&nbsp;</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
	
			{ text: '定番｜白透過・背景固定', data: '<table class="fullwidth_std_white" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2020/01/beach-bench-boardwalk-clouds.jpg\'); background-position: center; background-attachment: fixed;">\n<tbody>\n<tr>\n<td>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>&nbsp;</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n<p>テキストを入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			]},


	{ text: 'その他の枠', menu: [
			{ text: 'Q&A枠', data: '<table class="shikaku" style="border: 0px; box-shadow: 4px 4px 8px 3px rgba(100,100,100,0.5);">\n<tbody>\n<tr>\n<td>\n<p>&nbsp;</p>\n<p><img class="alignnone" src="https://lptemp.com/dx/wp-content/uploads/qanda.png" alt="" width="500" height="111" /></p>\n<hr />\n<p>&nbsp;</p>\n<table style="background-color: #f0f0f0; height: 100px;">\n<tbody>\n<tr>\n<td style="padding-left: 5px; width: 80px; vertical-align: top;">\n<p><img class="alignleft" src="https://lptemp.com/dx/wp-content/uploads/question.png" alt="" width="70" height="70" /></p>\n</td>\n<td style="padding: 10px 10px;">\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<table style="height: 100px;">\n<tbody>\n<tr>\n<td style="padding-left: 5px; width: 80px; vertical-align: top;">\n<p><img class="alignleft" src="https://lptemp.com/dx/wp-content/uploads/answer.png" alt="" width="70" height="70" /></p>\n</td>\n<td style="padding: 10px 10px;">\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: 'Q&A_1セット', data: '<table style="background-color: #f0f0f0; height: 100px;">\n<tbody>\n<tr>\n<td style="padding-left: 5px; width: 80px; vertical-align: top;">\n<p><img class="alignleft" src="https://lptemp.com/dx/wp-content/uploads/question.png" alt="" width="70" height="70" /></p>\n</td>\n<td style="padding: 10px 10px;">\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<table style="height: 100px;">\n<tbody>\n<tr>\n<td style="padding-left: 5px; width: 80px; vertical-align: top;">\n<p><img class="alignleft" src="https://lptemp.com/dx/wp-content/uploads/answer.png" alt="" width="70" height="70" /></p>\n</td>\n<td style="padding: 10px 10px;">\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: '表(ラインあり)', data: '<table class="line">\n<tbody>\n<tr>\n<td><p>テキスト</p></td>\n<td><p>テキスト</p></td>\n</tr>\n<tr>\n<td><p>テキスト</p></td>\n<td><p>テキスト</p></td>\n</tr>\n<tr>\n<td><p>テキスト</p></td>\n<td><p>テキスト</p></td>\n</tr>\n<tr>\n<td><p>テキスト</p></td>\n<td><p>テキスト</p></td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		]},



	{ text: 'その他', menu: [
			{ text: '特商法等の記載', data: '<p style="text-align: center;"><span style="font-size: 12px;"><a href="#" target="_blank">特定商取引法の表記</a>　｜　<a href="#" target="_blank">プライバシーポリシー</a>　｜　<a href="#" target="_blank">利用規約</a></span></p>'},
			{ text: 'コピーライト', data: '<p style="text-align: center;"><span style="font-size: 12px;">Copyright (C) 20○○ あなたの社名など All Rights Reserved.</span></p>'},
			{ text: '大きいサイズの文字', data: '<p style="font-size: 80px;">大きいサイズ</p>'},
			{ text: 'ページ内カウントダウン', data: '<p>[innerCountdown]</p>\n<p>&nbsp;</p>'},
		]},


	];


	// 旧パーツ
	var csMenuItems2 = [
		{ text: 'ヘッド(白字・画像背景)', data: '<table class="head-w" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2013/11/headback_moutain.jpg\'); height: 400px;" border="0">\n<tbody>\n<tr>\n<td>\n<p><span style="font-size: 60px;">ヘッドの文字を入力</span></p>\n<p>補足説明</p>\n<p>補足説明</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'ヘッド(黒字・画像背景)', data: '<table class="head-b" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2013/11/headback_letter1.jpg\'); height: 400px;" border="0">\n<tbody>\n<tr>\n<td>\n<p><span style="font-size: 60px;">ヘッドの文字を入力</span></p>\n<p>補足説明</p>\n<p>補足説明</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'サブヘッド(白字)', data: '<table class="obi" style="background-color: #ce1219;" border="0">\n<tbody>\n<tr>\n<td>\n<p>文字</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'サブヘッド(黒字)', data: '<table class="obi-b" style="background-color: #ffff33;" border="0">\n<tbody>\n<tr>\n<td>\n<p>文字</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '斜め型サブヘッド(白字)', data: '<table class="tape" style="background-color: #ce1219;" border="0">\n<tbody>\n<tr>\n<td>\n<p>文字</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '小見出し', data: '<table style="background-color: #f0f0f0;  height: 70px;">\n<tbody>\n<tr>\n<td style="padding: 0 10px;"><p>テキストを入力</p></td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'フォーム大', data: '<table class="submit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 370px;" border="2" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<p><img class="aligncenter size-full wp-image-32" alt="torokuword1" src="https://lptemp.com/dx/wp-content/uploads/2013/11/torokuword1.png" width="800" height="104" /></p>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input type="hidden" name="mid" value="example" /> <input type="hidden" name="fid" value="example" /> <input type="hidden" name="charcode" value="auto" /><dl><dt>名前</dt><dd><input style="color: #969696; font-size: 100%;" type="text" name="d[1]" placeholder="名前を入力" value="" /></dd><dt>メールアドレス</dt><dd><input style="color: #969696; font-size: 100%;" type="text" name="d[0]" placeholder="メールアドレスを入力" value="" /></dd></dl>\n<div class="btn"><input class="btn-blue" type="submit" name="submit" value="　登録　" /></div>\n</form></td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'フォーム小', data: '<table class="submit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 370px; width: 420px;" border="2" frame="border" rules="all" align="right">\n<tbody>\n<tr>\n<td style="width: 380px;"><form action="https://yahoo.co.jp/" method="post" target="_blank"><input type="hidden" name="mid" value="example" /><input type="hidden" name="fid" value="example" /> <input type="hidden" name="charcode" value="auto" /><dl><dt>名前</dt><dd></dd><dd><input style="color: #969696; font-size: 100%;" type="text" name="d[1]" placeholder="名前を入力" value="" /></dd><dt>メールアドレス</dt><dd><input  style="color: #969696; font-size: 100%;" type="text" name="d[0]" placeholder="メールアドレスを入力" value="" /></dd></dl>\n<div class="btn"><input class="btn-blue-sma" type="submit" name="submit" value="　登録　" /></div>\n</form></td>\n</tr>\n</tbody>\n</table>\n<p><img class="alignnone size-full wp-image-75" alt="torokuword-sma1" src="https://lptemp.com/dx/wp-content/uploads/2013/11/torokuword-sma1.png" width="370" height="400" /></p>\n<p>&nbsp;</p>'},
		{ text: 'フォーム大(ボタン画像ver)', data: '<table class="submit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 370px;" border="2" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<p><img class="aligncenter size-full wp-image-32" alt="torokuword1" src="https://lptemp.com/dx/wp-content/uploads/2013/11/torokuword1.png" width="800" height="104" /></p>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input type="hidden" name="mid" value="example" /> <input type="hidden" name="fid" value="example" /> <input type="hidden" name="charcode" value="auto" /><dl><dt>名前</dt><dd><input style="color: #969696; font-size: 100%;" type="text" name="d[1]" placeholder="名前を入力" value="" /></dd><dt>メールアドレス</dt><dd><input  style="color: #969696; font-size: 100%;" type="text" name="d[0]" placeholder="メールアドレスを入力" value=""  /></dd></dl>\n<div class="btn"><input type="image" name="submit" src="https://lptemp.com/dx/wp-content/uploads/2013/11/button1_blue_big.jpg" value="　今すぐ無料で登録する　" /></div>\n</form></td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'フォーム小(ボタン画像ver)', data: '<table class="submit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 370px; width: 420px;" border="2" frame="border" rules="all" align="right">\n<tbody>\n<tr>\n<td style="width: 380px;"><form action="https://yahoo.co.jp/" method="post" target="_blank"><input type="hidden" name="mid" value="example" /><input type="hidden" name="fid" value="example" /><input type="hidden" name="charcode" value="auto" /><dl><dt>名前</dt><dd></dd><dd><input style="color: #969696; font-size: 100%;" type="text" name="d[1]" placeholder="名前を入力" value=""  /></dd><dt>メールアドレス</dt><dd><input style="color: #969696; font-size: 100%;" type="text" name="d[0]" placeholder="メールアドレスを入力" value="" /></dd></dl>\n<div class="btn"><input type="image" name="submit" src="https://lptemp.com/dx/wp-content/uploads/2013/11/button1_blue_sma.jpg" value="　今すぐ無料で登録する　" /></div>\n</form></td>\n</tr>\n</tbody>\n</table>\n<p><img class="alignnone size-full wp-image-75" alt="torokuword-sma1" src="https://lptemp.com/dx/wp-content/uploads/2013/11/torokuword-sma1.png" width="370" height="400" /></p>\n<p>&nbsp;</p>'},
		
		
		
				{ text: 'フォーム・デザインWIDE', data: '<table class="submit" style="border: 2px solid #ccc; background-color: #f3f1f2; height: 370px;" border="2" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<p><img class="aligncenter size-full wp-image-32" src="https://lptemp.com/dx/wp-content/uploads/2013/11/torokuword1.png" alt="torokuword1" width="800" height="104" /></p>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<p><input class="fd01wide" style="color: #969696; font-size: 100%;" placeholder="名前を入力" name="d[1]" type="text" value="" /></p>\n<p><input class="fd01wide" style="color: #969696; font-size: 100%;" placeholder="メールアドレスを入力" name="d[0]" type="text" value="" /></p>\n<div class="btn"><input class="btn-skewlr-blue" style="width: 740px; height: 60px;" name="submit" type="submit" value="　無料登録する　" /></div>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
				
				
							{ text: 'フォーム・デザインWIDE(画像ver)', data: '<table class="submit" style="border: 2px solid #ccc; background-color: #f3f1f2; height: 370px;" border="2" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<p><img class="aligncenter size-full wp-image-32" src="https://lptemp.com/dx/wp-content/uploads/2013/11/torokuword1.png" alt="torokuword1" width="800" height="104" /></p>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" /> <input name="charcode" type="hidden" value="auto" />\n<p><input class="fd01wide" style="color: #969696; font-size: 100%;" placeholder="名前を入力" name="d[1]" type="text" value="" /></p>\n<p><input class="fd01wide" style="color: #969696; font-size: 100%;" placeholder="メールアドレスを入力" name="d[0]" type="text" value="" /></p>\n<div class="btn"><input type="image" name="submit" src="https://lptemp.com/dx/wp-content/uploads/2016/12/formbutton-wide.png" value="　今すぐ無料で登録する　" /></div>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
				
					
				
								{ text: 'フォーム・デザインFLAT', data: '<table class="submit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 370px;" border="2" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<p><img class="aligncenter size-full wp-image-32" src="https://lptemp.com/dx/wp-content/uploads/2013/11/torokuword1.png" alt="torokuword1" width="800" height="104" /></p>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" />\n<input name="charcode" type="hidden" value="auto" />\n<p><input class="fd02flat" style="color: #969696; font-size: 100%;" placeholder="名前を入力" name="d[1]" type="text" value="" /></p>\n<p><input class="fd02flat" style="color: #969696; font-size: 100%;" placeholder="メールアドレスを入力" name="d[0]" type="text" value="" /></p>\n<div class="btn"><input class="btn-gelatin-blue" name="submit" type="submit" value="　登録　" /></div>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
				
				
					{ text: 'フォーム・デザインFLAT(画像ver)', data: '<table class="submit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 370px;" border="2" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<p><img class="aligncenter size-full wp-image-32" src="https://lptemp.com/dx/wp-content/uploads/2013/11/torokuword1.png" alt="torokuword1" width="800" height="104" /></p>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input name="mid" type="hidden" value="example" /> <input name="fid" type="hidden" value="example" />\n<input name="charcode" type="hidden" value="auto" />\n<p><input class="fd02flat" style="color: #969696; font-size: 100%;" placeholder="名前を入力" name="d[1]" type="text" value="" /></p>\n<p><input class="fd02flat" style="color: #969696; font-size: 100%;" placeholder="メールアドレスを入力" name="d[0]" type="text" value="" /></p>\n<div class="btn"><input type="image" name="submit" src="https://lptemp.com/dx/wp-content/uploads/2016/12/formbutton-flat.png" value="　今すぐ無料で登録する　" /></div>\n</form>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
				
		
		
		
		{ text: '枠・ブレッド(四角)', data: '<table class="shikaku" style="border: 1px solid #000000;" border="1">\n<tbody>\n<tr>\n<td>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '枠・ブレッド(角丸)', data: '<table class="marukaku" style="border: 1px solid #000000;" border="1">\n<tbody>\n<tr>\n<td>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '枠・ブレッド(へこみ)', data: '<table class="pressed">\n<tbody>\n<tr>\n<td>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '枠・ブレッド(浮出)', data: '<table class="tableshadow">\n<tbody>\n<tr>\n<td>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n<p><img src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" alt="" width="32" height="32" />　ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: 'ブレッド追加', data: '<p><img alt="" src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />　ここに文字を入力</p>'},
		
		
		{ text: 'Q&A枠', data: '<table class="shikaku" style="border: 0px; box-shadow: 4px 4px 8px 3px rgba(100,100,100,0.5);">\n<tbody>\n<tr>\n<td>\n<p>&nbsp;</p>\n<p><img class="alignnone" src="https://lptemp.com/dx/wp-content/uploads/qanda.png" alt="" width="500" height="111" /></p>\n<hr />\n<p>&nbsp;</p>\n<table style="background-color: #f0f0f0; height: 100px;">\n<tbody>\n<tr>\n<td style="padding-left: 5px; width: 80px; vertical-align: top;">\n<p><img class="alignleft" src="https://lptemp.com/dx/wp-content/uploads/question.png" alt="" width="70" height="70" /></p>\n</td>\n<td style="padding: 10px 10px;">\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<table style="height: 100px;">\n<tbody>\n<tr>\n<td style="padding-left: 5px; width: 80px; vertical-align: top;">\n<p><img class="alignleft" src="https://lptemp.com/dx/wp-content/uploads/answer.png" alt="" width="70" height="70" /></p>\n</td>\n<td style="padding: 10px 10px;">\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		
		{ text: 'Q&A_1セット', data: '<table style="background-color: #f0f0f0; height: 100px;">\n<tbody>\n<tr>\n<td style="padding-left: 5px; width: 80px; vertical-align: top;">\n<p><img class="alignleft" src="https://lptemp.com/dx/wp-content/uploads/question.png" alt="" width="70" height="70" /></p>\n</td>\n<td style="padding: 10px 10px;">\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<table style="height: 100px;">\n<tbody>\n<tr>\n<td style="padding-left: 5px; width: 80px; vertical-align: top;">\n<p><img class="alignleft" src="https://lptemp.com/dx/wp-content/uploads/answer.png" alt="" width="70" height="70" /></p>\n</td>\n<td style="padding: 10px 10px;">\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		
	
		
		{ text: 'ボタン(青大)', data: '<p class="btn-blue"><a href="https://yahoo.jp" target="blank">ここに好きな文字を入力</a></p>\n<p>&nbsp;</p>'},
		{ text: 'ボタン(青小)', data: '<p class="btn-blue-sma"><a href="https://yahoo.jp"target="blank">ここに好きな文字を入力</a></p>\n<p>&nbsp;</p>'},
		{ text: '動くボタン(青)', data: '<p class="btn-skewlr-blue"><a href="https://yahoo.jp"target="blank">ここに好きな文字を入力</a></p>\n<p>&nbsp;</p>'},
		{ text: '触ると動くボタン(青)', data: '<p class="btn-gelatin-blue"><a href="https://yahoo.jp"target="blank">ここに好きな文字を入力</a></p>\n<p>&nbsp;</p>'},
		{ text: 'ボタン・カスタマイズ用(青)', data: '<p class="btn-custom" style="background: #1253A4;"><span style="color: #fff;"><strong><a href="https://yahoo.jp" target="blank">ここに好きな文字を入力</a></strong></span></p>'},
		{ text: 'チェックマーク(緑)', data: '<img alt="1540_32" src="https://lptemp.com/dx/wp-content/uploads/2013/11/check_green.png" width="32" height="32" />'},
		{ text: '下矢印(青)', data: '<img  src="https://lptemp.com/dx/wp-content/uploads/2013/11/allow.jpg" />'},
		{ text: '特商法等の記載', data: '<p style="text-align: center;"><span style="font-size: 8pt;"><a href="https://yahoo.co.jp" target="_blank">特定商取引法の表記</a>　｜　<a href="https://yahoo.co.jp" target="_blank">プライバシーポリシー</a>　｜　<a href="https://yahoo.co.jp" target="_blank">利用規約</a></span></p>'},
		{ text: 'コピーライト', data: '<p style="text-align: center;"><span style="font-size: 10pt;">Copyright (C) 20○○ あなたの社名など All Rights Reserved.</span></p>'},
		{ text: '大きいサイズの文字', data: '<p style="font-size: 80px;">大きいサイズ</p>'},
		
		{ text: 'ホバーサンプル1', data: '<p style="text-align: center;"><strong style="font-size: 40px;">ちょっと待ってください</strong></p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>&nbsp;</p>\n<table class="formsubmit" style="border: 2px solid #000000; background-color: #f3f1f2; height: 250px;" border="2" frame="box" rules="all" align="center">\n<tbody>\n<tr>\n<td>\n<p><img class="aligncenter size-full wp-image-32" alt="torokuword1" src="https://lptemp.com/dx/wp-content/uploads/2013/11/torokuword1.png" width="500" /></p>\n<form action="https://yahoo.co.jp/" method="post" target="_blank"><input type="hidden" name="mid" value="example" /> <input type="hidden" name="fid" value="example" /> <input type="hidden" name="charcode" value="auto" /><dl><dt>名前</dt><dd><input style="color: #969696; font-size: 70%;" name="d[1]" type="text" placeholder="名前を入力" /></dd><dt>メールアドレス</dt><dd><input style="color: #969696; font-size: 70%;" name="d[0]" type="text" placeholder="メールアドレスを入力" /></dd></dl>\n<div class="btn"><input type="submit" name="submit" value="　　無料で登録する　　" /></div>\n</form></td>\n</tr>\n</tbody>\n</table>'},
		
		{ text: '表(ラインあり)', data: '<table class="line">\n<tbody>\n<tr>\n<td><p>テキスト</p></td>\n<td><p>テキスト</p></td>\n</tr>\n<tr>\n<td><p>テキスト</p></td>\n<td><p>テキスト</p></td>\n</tr>\n<tr>\n<td><p>テキスト</p></td>\n<td><p>テキスト</p></td>\n</tr>\n<tr>\n<td><p>テキスト</p></td>\n<td><p>テキスト</p></td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '枠(幅いっぱい)', data: '<table class="wide" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2013/12/rockywall.png\'); ">\n<tbody>\n<tr>\n<td>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
			{ text: '斜め型枠(幅いっぱい)', data: '<table class="wide tilt" style="background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2013/12/rockywall.png\'); ">\n<tbody>\n<tr>\n<td>\n<p>&nbsp;</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>&nbsp;</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>&nbsp;</p>'},
		{ text: '(高度)全幅ヘッド', data: '<div class="full-width">\n<table class="head-w" style="border-width: 0px; border-style: solid; background-image: url(\'https://lptemp.com/dx/wp-content/uploads/2014/10/blur-background13.jpg\');  background-position: 50% 0; height: 400px;" border="0">\n<tbody>\n<tr>\n<td>\n<p><span style="font-size: 60px;">ヘッドの文字を入力</span></p>\n<p>補足説明</p>\n<p>補足説明</p>\n</td>\n</tr>\n</tbody>\n</table>\n</div>\n<p>&nbsp;</p>'},
		{ text: '(高度)全幅サブヘッド', data: '<div class="full-width">\n<table class="obi" style="background-color: #ce1219;" border="0">\n<tbody>\n<tr>\n<td>\n<p>文字</p>\n</td>\n</tr>\n</tbody>\n</table>\n</div>\n<p>&nbsp;</p>'},
		{ text: '(高度)全幅枠', data: '<div class="full-width">\n<table style="background-color: #ffd464;   background-position: 50% 0; border-width: 0px; border-style: solid;" border="0">\n<tbody>\n<tr>\n<td>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n</td>\n</tr>\n</tbody>\n</table>\n</div>\n<p>&nbsp;</p>'},
			{ text: '(高度)斜め型全幅枠', data: '<div class="full-width">\n<table class="tilt" style="background-color: #ffd464;   background-position: 50% 0; border-width: 0px; border-style: solid;" border="0">\n<tbody>\n<tr>\n<td>\n<p>&nbsp;</p>\n<p>ここに文字を入力</p>\n<p>ここに文字を入力</p>\n<p>&nbsp;</p>\n</td>\n</tr>\n</tbody>\n</table>\n</div>\n<p>&nbsp;</p>'},
		{ text: 'ページ内カウントダウン', data: '<p>[innerCountdown]</p>\n<p>&nbsp;</p>'},
			
	];




	function insertTag(data) {
		editor.insertContent(data);
	}

	editor.addButton('taglist', {
		type: 'menubutton',
		text: 'カスタムボタン',
		icon: false,
		menu: csMenuItems,
		onselect: function(e) {
			insertTag(e.control.settings.data);
		},
	});

	editor.addButton('taglist2', {
		type: 'menubutton',
		text: 'カスタムボタン(旧)',
		icon: false,
		menu: csMenuItems2,
		onselect: function(e) {
			insertTag(e.control.settings.data);
		},
	});
});
